extends Node


"""
/////////////////////////
API Connection Tags and States
/////////////////////////
"""
const MSGTAG_ROOM_REFRESH = "ROOM_TAG_REFRESH"
const MSGTAG_ROOM_JOIN = "ROOM_TAG_JOIN"
const MSGTAG_ROOM_RESET = "ROOM_TAG_RESET"
const MSGTAG_ROOM_OCCUPIED = "ROOM_TAG_OCCUPIED"

const STATE_ROOM_EMPTY = "ROOM_STATE_EMPTY"
const STATE_ROOM_WAITING = "ROOM_STATE_WAITING"
const STATE_ROOM_STARTING = "ROOM_STATE_STARTING"
const STATE_ROOM_OCCUPIED = "ROOM_STATE_OCCUPIED"

const CLIENT_STATE_PLAYING = "CLIENT_STATE_PLAYING"
const CLIENT_STATE_WAITING = "CLIENT_STATE_WAITING"
const CLIENT_STATE_ONLINE = "CLIENT_STATE_ONLINE"

const MSGTAG_SERVER_ROOMS = "SERVER_TAG_GET_ROOMS"
const MSGTAG_SERVER_PLAYER_NUMBERS = "SERVER_TAG_P_NUMBERS"
const MSGTAG_SERVER_PLAYER_DATA = "SERVER_TAG_P_DATA"

const REQUEST_JOIN_ROOM = "REQUEST_JOIN_ROOM"

"""
/////////////////////////
Battle Constants
/////////////////////////
"""

#Action Target Type
const ACTION_TARGET_TYPE_HEX = "HEX_TARGET"
const ACTION_TARGET_TYPE_SELF = "SELF_TARGET"
const ACTION_TARGET_TYPE_SINGLE = "SINGLE_TARGET"
const ACTION_TARGET_TYPE_AREA = "AREA_TARGET"
const ACTION_TARGET_TYPE_LINE = "LINE_TARGET"
const ACTION_TARGET_TYPE_CONE = "CONE_TARGET"

